export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home
export JAVA_HOME=$(/usr/libexec/java_home)
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
PATH=$PATH:$JAVA_HOME

M2_HOME=path to apache-maven-3.5.3 folder
PATH=$PATH:$M2_HOME/bin

VENV=path to venv folder
PATH=$PATH:$VENV

SHELL=path to shell folder
PATH=$PATH:$SHELL


>> echo $PATH

/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home:path to apache-maven-3.5.3 folder/bin:path to venv folder:path to shell folder
