#!/bin/bash
configFilePath=/custom/cmd-config.txt
venvFolder=$(sed -n "1p" $configFilePath)

runCommandFolder=$(sed -n "3p" "$venvFolder"cmd-config.txt)

echo ****************Starting application****************
cd $runCommandFolder
sh run.bat
echo ****************Application stoped****************
