---
taskComponents:
  _1:
    name: Task-1-component-1
  _2:
    name: Task-1-component-2
  _3:
    name: Task-1-component-3
  _111:
    name: Task-1-component-1
  _112:
    name: Task-1-component-1
  _114:
    name: Task-1-component-1
