---
taskItems:
  - id: _1
    component: [_1, _2, _3]
    options:
      name: Task-1
      location: Task-1 Place
  - id: _2
    component: [_4, _5]
    options:
      name: Task-2
      location: Task-2 Place
  - id: _3
    component: [_6, _7, _8]
    options:
      name: Task-3
      location: Task-3 Place
  - id: _4
    component: []
    options:
      name: Task-4
      location: Task-4 Place
