---
taskItems:
  - id: 104
    component: ["id:string=_1|name:string[]=_hello,world", "id:string=_2|name:string=world", _3]
    options:
      name: Task-1
      location: Task-1 Place
    history:
      - date: 2017-06-05
        field_1: Done some thing different
      - date: 2017-06-05
        field_1: Observed some thing different
        obervation: Something different
      - str_1: 2017-06-04
        str_2: Observed some thing repeated
        str_3: Something old
  - id: 102
    component: [_4, _5]
    options:
      name: Task-2
      location: Task-2 Place
  - id: 103
    component: [_6, _7, _8]
    options:
      name: Task-3
      location: Task-3 Place
  - id: 101
    component: []
    options:
      name: Task-4
      location: Task-4 Place
