---
taskItems:
  - id: 111
    component: [_111, _112, _113]
    options:
      name: Task-1
      location: Task-2 Place
  - id: 113
    component: [_114, _115]
    options:
      name: Task-2
      location: Task-2 Place
  - id: 112
    component: [_116, _117, _118]
    options:
      name: Task-3
      place: Task-3 Place
  - id: 114
    component: []
    options:
      name: Task-4
      place: Task-4 Place
