---
taskApplications:
  - id: app-1
    path:
      path-1: [[_1],[_2], [_3, _111]]
      path-2: [[_112],[_2], [_118], ["can be done anything"]]
    options:
      x: y
  - id: app-2
    path:
      path-1: [[_1],[_2], [_3, _111]]
      path-2: [[_112],[_2], [_118], ["can be done anything"]]
    options:
      x: y
