# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  host: localhost
  username: root
  password: ''
  database: tests
# DB_DEFAULTS = { :adapter => 'mysql2', :encoding => 'utf8', :reconnect => true, :database => "tests", :pool => 25, :username => 'root', :password => '', :host => 'localhost'}

# ActiveRecord::Base.configurations[:development] = DB_DEFAULTS

# # Setup our logger
# ActiveRecord::Base.logger = logger

# # Include Active Record class name as root for JSON serialized output.
# ActiveRecord::Base.include_root_in_json = false

# # Store the full class name (including module namespace) in STI type column.
# ActiveRecord::Base.store_full_sti_class = true
# ActiveRecord::Base.establish_connection(ActiveRecord::Base.configurations["development"])
# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
