# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba26904dceaebbc9ab9581f15f1d36bf0f0d6df203ab20f58cf47a6a3419b078d6dc1c21f8beeef1b275e811cd71a5166bafe559bce0de1355de657be5f8379d

test:
  secret_key_base: 73b8474a6deaa6894f17bf8a145f1985d636fb213816ae46917622c048ce4cb1846ec4e421e2c2e7c28466b0978cc7e0250ea0b2f14df28d762c89c8e2815250

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
