logging:
  level: INFO
  loggers:
    com.todo: INFO
  appenders:
    - type: console
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{X-Session-Id} - %X{X-Request-Id}] - %c{15} - %msg%n%rEx"
      threshold: ALL
      timeZone: UTC
    - type: file
      threshold: ALL
      timeZone: UTC
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{X-Session-Id} - %X{X-Request-Id}] - %c{15} - %msg%n%rEx"
      currentLogFilename: D:/workspace/project/ftp-app/log/application.log
      archivedLogFilenamePattern: D:/workspace/project/ftp-app/log/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 5

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    port: 8080
    type: http
  rootPath: /*

supportedFileType:
  - pdf
  - txt
  - docx
  - doc
  - xlsx
  - xls
  - pptx
  - ppt
  - mp3
  - mp4
  - exe

filenameFormat: "YYYY-MM-dd'-filename'"
fileSaveDir: D:/workspace/project/ftp-app/saved-files/
icoFilePath: meta-data/favicon.ico
maxFileSize: 2048001 #i.e. 2048 kB or 2MB

adminUsersName:
  - Admin

# Only for development purpose
permanentlyDeleteFile: false
createReadmePdf: true
indexPageReRoute: /dashboard
appViewFtlFileName: app_view.ftl
publicDir: "../.."
publicPostDir:
allowedOrigin:
  - http://localhost
  - http://localhost:9000
  - http://localhost:8080
devUsersName:
  - U1
tempConfig:
  username: U1
