---
resources:
  - name: Index page
    url: /
    help: /
  - name: View Dashboard
    url: /view/dashboard
    help: /view/dashboard
  - name: View Config
    url: /view/config
    help: /view/config
  - url: /view/todo/all
    name: View all todo
    help: /view/todo/all
  - url: /view/todo/id/1
    name: View todo by Id
    help: /view/todo/id/{id}
  - url: /todo/api/v1/all
    name: Get all todo
    help: /todo/api/v1/all
  - url: /todo/api/v1/id/1
    name: Get todo by Id
    help: /todo/api/v1/id/1
  - url: /todo/api/v1/socket?query=127.0.0.1!!!8000!!!test|END
    name: Call socket
    help: /todo/api/v1/socket?query=127.0.0.1!!!8000!!!test|END
  - url: /config/api/v1/yaml
    name: "[data] Get yaml object"
    help: /config/api/v1/yaml
  - url: /config/api/v1/resource
    name: "[data] Available resource"
    help: /config/api/v1/resource
  - url: /config/api/v1/get/task
    name: "[data] Get task config"
    help: /config/api/v1/get/task
  - url: /config/api/v1/update/task
    name: "[data] Update task config"
    help: /config/api/v1/update/task
  - url: /config/api/v1/get/files
    name: "[data] Get file config"
    help: /config/api/v1/get/files
  - url: /config/api/v1/update/files
    name: "[data] Update file config"
    help: /config/api/v1/update/files
  - url: /files/v1/upload/view
    name: File upload view
    help: /files/v1/upload/view
  - url: /files/v1/query/view
    name: File query view
    help: /files/v1/query/view
  - url: /files/v1/query/submit
    name: File query submit
    help: /files/v1/query/submit
  - url: /files/v1/static?name=static-file-name
    name: Load static file
    help: /files/v1/static?name={file-name}
  - url: /files/v1/get/data/test.txt?name=test.txt
    name: File - data
    help: /files/v1/get/data/test.txt?name={file-name}
  - url: /files/v1/get/view/test.txt?name=test.txt
    name: File - view
    help: /files/v1/get/view/test.txt?name={file-name}
  - url: /files/v1/get/download?name=test.txt
    name: File - download
    help: /files/v1/get/download?name={file-name}
  - url: /files/v1/filter/data?type=txt,csv
    name: Filter - data
    help: /files/v1/filter/data?type=txt,csv
  - url: /files/v1/filter/view?type=txt,csv
    name: Filter - view
    help: /files/v1/filter/view?type=txt,csv
  - url: /files/v2/getAll/data
    name: Get all - v2 - data
    help: /files/v2/getAll/data
  - url: /files/v2/getAll/view
    name: Get all - v2 - view
    help: /files/v2/getAll/view
  - url: /files/v2/getAll/index/0/data
    name: Get all - index - 0 - v2 - data
    help: /files/v2/getAll/index/{id}/data
  - url: /files/v2/getAll/index/0/view
    name: Get all - index - 0 - v2 - view
    help: /files/v2/getAll/index/{id}/view
  - url: /files/v3/getAll/data
    name: Get all - v3 - data
    help: /files/v3/getAll/data
  - url: /files/v3/getAll/view
    name: Get all - v3 - view
    help: /files/v3/getAll/view
  - url: /files/v3/getAll/index/0/data
    name: Get all - index - 0 - v3 - data
    help: /files/v3/getAll/index/{id}/data
  - url: /files/v3/getAll/index/0/view
    name: Get all - index - 0 - v3 - view
    help: /files/v3/getAll/index/{id}/view?path={path-to-folder-or-file-or-null}
  - url: /task/api/v1/tasks
    name: Get all task - v1
    help: /task/api/v1/tasks
  - url: /task/api/v2/tasks
    name: Get all task - v2
    help: /task/api/v2/tasks
  - url: /task/api/v3/tasks
    name: Get all task - v3
    help: /task/api/v3/tasks
  - url: /task/api/v1/tasks/_1
    name: Get task by id - v1
    help: /task/api/v1/tasks/{id}
  - url: /task/api/v2/tasks/_1
    name: Get task by id - v2
    help: /task/api/v2/tasks/{id}
  - url: /task/api/v3/tasks/_1
    name: Get task by id - v3
    help: /task/api/v3/tasks/{id}
  - url: /task/api/v1/components
    name: Get all component
    help: /task/api/v1/components
  - url: /task/api/v1/components/_1
    name: Get component by id - v1
    help: /task/api/v1/components/{id}
  - url: /task/api/v2/components/_1
    name: Get component by id - v2
    help: /task/api/v2/components/{id}
  - url: /task/api/v3/components/_1
    name: Get component by id - v3
    help: /task/api/v3/components/{id}
  - url: /task/api/v1/app/all
    name: Get all app - v1
    help: /task/api/v1/app/all
  - url: /task/api/v2/app/all
    name: Get all app - v2
    help: /task/api/v2/app/all
  - url: /task/api/v3/app/all
    name: Get all app - v3
    help: /task/api/v3/app/all
  - url: /task/api/v1/app/id/app-1
    name: Get app by id - v1
    help: /task/api/v1/app/id/{id}
  - url: /task/api/v2/app/id/app-1
    name: Get app by id - v2
    help: /task/api/v2/app/id/{id}
  - url: /task/api/v3/app/id/app-1
    name: Get app by id - v3
    help: /task/api/v3/app/id/{id}
