---
resources:
  - name: Index page
    url: /
    help: /
  - name: View Dashboard
    url: /view/dashboard
    help: /view/dashboard
  - name: View Config
    url: /view/config
    help: /view/config
#  - name: View Build
#    url: /view/build
#    help: /view/build
  - name: View Resource
    url: /view/resource
    help: /view/resource
  - url: /view/todo/all
    name: View all todo
    help: /view/todo/all
  - url: /view/todo/id/1
    name: View todo by Id
    help: /view/todo/id/{id}
  - url: /todo/api/v1/all
    name: Get all todo
    help: /todo/api/v1/all
  - url: /todo/api/v1/id/1
    name: Get todo by Id
    help: /todo/api/v1/id/1
  - url: /todo/api/v1/socket?query=127.0.0.1!!!8000!!!test|END
    name: Call socket
    help: /todo/api/v1/socket?query=127.0.0.1!!!8000!!!test|END
  - url: /todo/api/v1/socket/v2?query=test|END&service=self
    name: Call socket v2
    help: /todo/api/v1/socket/v2?query=test|END&service=self
  - url: /config/api/v1/yaml
    name: "[data] Get yaml object"
    help: /config/api/v1/yaml
  - url: /config/api/v1/resource
    name: "[data] Available resource"
    help: /config/api/v1/resource
  - url: /config/api/v1/get/app-config
    name: "[data] Get App Config"
    help: /config/api/v1/get/app-config
  - url: /config/api/v1/update/app-config
    name: "[data] Update App Config"
    help: /config/api/v1/update/app-config
  - url: /config/api/v1/get/task
    name: "[data] Get task config"
    help: /config/api/v1/get/task
  - url: /config/api/v1/update/task
    name: "[data] Update task config"
    help: /config/api/v1/update/task
  - url: /config/api/v1/get/files
    name: "[data] Get file config"
    help: /config/api/v1/get/files
  - url: /config/api/v1/get/project-static-data
    name: "[data] Get project-static-data"
    help: /config/api/v1/get/project-static-data
  - url: /config/api/v1/update/project-static-data
    name: "[data] Update project-static-data"
    help: /config/api/v1/update/project-static-data
#  - url: /config/api/v1/update/files
#    name: "[data] Update file config"
#    help: /config/api/v1/update/files
  - url: /config/api/v1/get/client-details
    name: "[data] Get client details"
    help: /config/api/v1/get/client-details
  - url: /files/v1/upload/view
    name: File upload view
    help: /files/v1/upload/view
  - url: /files/v1/query/view
    name: File query view
    help: /files/v1/query/view
  - url: /files/v1/add_text?text=hello&fileName=test.txt
    name: "[Get]Add new line to file"
    help: /files/v1/add_text?text=hello&fileName=test.txt
  - url: /files/v1/query/submit
    name: File query submit
    help: /files/v1/query/submit
  - url: /files/v1/static?name=static-file-name
    name: Load static file
    help: /files/v1/static?name={file-name}
  - url: /files/v1/get/data/test.txt?name=test.txt
    name: File - data
    help: /files/v1/get/data/test.txt?name={file-name}
  - url: /files/v1/get/view/test.txt?name=test.txt
    name: File - view
    help: /files/v1/get/view/test.txt?name={file-name}
  - url: /files/v1/download/view/file-name?name=test.txt
    name: File - download
    help: /files/v1/download/view/file-name?name={file-name}
  - url: /files/v1/get/download?name=test.txt
    name: File - download
    help: /files/v1/get/download?name={file-name}
  - url: /files/v1/get/download/file-name?name=test.txt
    name: File - download
    help: /files/v1/get/download/file-name?name={file-name}
  - url: /files/v1/filter/data?type=txt,csv
    name: Filter - data
    help: /files/v1/filter/data?type=txt,csv
  - url: /files/v1/filter/view?type=txt,csv
    name: Filter - view
    help: /files/v1/filter/view?type=txt,csv
  - url: /files/v2/getAll/data
    name: Get all - v2 - data
    help: /files/v2/getAll/data
  - url: /files/v2/getAll/view
    name: Get all - v2 - view
    help: /files/v2/getAll/view
  - url: /files/v2/getAll/index/0/data
    name: Get all - index - 0 - v2 - data
    help: /files/v2/getAll/index/{id}/data
  - url: /files/v2/getAll/index/0/view
    name: Get all - index - 0 - v2 - view
    help: /files/v2/getAll/index/{id}/view
  - url: /files/v3/getAll/data
    name: Get all - v3 - data
    help: /files/v3/getAll/data
  - url: /files/v3/getAll/view
    name: Get all - v3 - view
    help: /files/v3/getAll/view
  - url: /files/v3/getAll/index/0/data
    name: Get all - index - 0 - v3 - data
    help: /files/v3/getAll/index/{id}/data
  - url: /files/v3/getAll/index/0/view
    name: Get all - index - 0 - v3 - view
    help: /files/v3/getAll/index/{id}/view?path={path-to-folder-or-file-or-null}
  - url: /task/api/v1/tasks
    name: Get all task - v1
    help: /task/api/v1/tasks
  - url: /task/api/v1/tasks/byid
    name: Get all task - v1 byid
    help: /task/api/v1/tasks/byid
  - url: /task/api/v2/tasks
    name: Get all task - v2
    help: /task/api/v2/tasks
  - url: /task/api/v3/tasks
    name: Get all task - v3
    help: /task/api/v3/tasks
  - url: /task/api/v1/tasks/_1
    name: Get task by id - v1
    help: /task/api/v1/tasks/{id}
  - url: /task/api/v2/tasks/_1
    name: Get task by id - v2
    help: /task/api/v2/tasks/{id}
  - url: /task/api/v3/tasks/_1
    name: Get task by id - v3
    help: /task/api/v3/tasks/{id}
  - url: /task/api/v1/component/all
    name: Get all component
    help: /task/api/v1/component/all
  - url: /task/api/v1/component/id/_1
    name: Get component by id - v1
    help: /task/api/v1/component/id/{id}
  - url: /task/api/v1/app/all
    name: Get all app - v1
    help: /task/api/v1/app/all
  - url: /task/api/v2/app/all
    name: Get all app - v2
    help: /task/api/v2/app/all
  - url: /task/api/v3/app/all
    name: Get all app - v3
    help: /task/api/v3/app/all
  - url: /task/api/v1/app/id/app-1
    name: Get app by id - v1
    help: /task/api/v1/app/id/{id}
  - url: /task/api/v2/app/id/app-1
    name: Get app by id - v2
    help: /task/api/v2/app/id/{id}
  - url: /task/api/v3/app/id/app-1
    name: Get app by id - v3
    help: /task/api/v3/app/id/{id}
  - url: /project
    name: Project Dashboard
    help: /project
  - url: /project/p0
    name: Project v0
    help: /project/p0
  - url: /project/p0/p1
    name: Project v1
    help: /project/p0/p1
  - url: /project/p0/p1/p2
    name: Project v2
    help: /project/p0/p1/p2
  - url: /project/p0/p1/p2/p3
    name: Project v3
    help: /project/p0/p1/p2/p3
  - url: /project/p0/p1/p2/p3/p4
    name: Project v4
    help: /project/p0/p1/p2/p3/p4
  - url: /project/p0/p1/p2/p3/p4/p5
    name: Project v5
    help: /project/p0/p1/p2/p3/p4/p5
  - url: /project/p0/p1/p2/p3/p4/p5/p6
    name: Project v6
    help: /project/p0/p1/p2/p3/p4/p5/p6
  - url: /project/p0/p1/p2/p3/p4/p5/p6/p7
    name: Project v7
    help: /project/p0/p1/p2/p3/p4/p5/p6/p7
  - url: /project/p0/p1/p2/p3/p4/p5/p6/p7/*
    name: Project (404)
    help: /project/p0/p1/p2/p3/p4/p5/p6/p7/* => 404