---
#relativePath: [meta-data/, meta-data/files/, meta-data/csv/, ../../templates/common/]
relativePath: [../../pendrive/docs-2017-02-18/]
unsupportedFileType: [jar, docx]
mimeType:
  png: image/png
  jpg: image/jpg
  jpeg: image/jpeg
  gif: image/gif
  txt: text/plain
  css: text/css
  csv: text/plain
  html: text/html
  htm: text/html
  htmls: text/html
  pdf: application/pdf
  json: application/json
  yaml: text/plain
  yml: text/plain