---
relativePath: [meta-data/files/, meta-data/csv/, uploaded_files/]
pathReplaceString:
  ../:
unsupportedFileType: [jar, docx]
messageSavePath: uploaded_files/
mimeType:
  png: image/png
  jpg: image/jpg
  jpeg: image/jpeg
  gif: image/gif
  css: text/css
  html: text/html
  htm: text/html
  htmls: text/html
  pdf: application/pdf
  json: application/json
  yaml: text/plain
  yml: text/plain
  csv: text/plain
  txt: text/plain
  sh: text/sh