roleAccess:
  ADMIN_USER:
    - Admin
  DEV_USERS:
    - SHISHUPAL
  PUBLIC_USERS:
    - public
roleAccessMapping:
  isAdminUser: ADMIN_USER
  isDevUser: DEV_USERS
  isDeleteFileEnable: true
  isUploadFileEnable: true
  isAdminTextDisplayEnable: (ADMIN_TEXT_DISPLAY_USERS|DEV_USERS)
  isLoginOtherUserEnable: DEV_USERS
  isUsersControlEnable: DEV_USERS
  isDevUser2: DEV_USERS

coRelatedUsers:
  - ADMIN_TEXT_DISPLAY_USERS
groupRelatedUsers:
  ADMIN_TEXT_DISPLAY_USERS:
    - APP_USERS
    - PUBLIC_USERS
  APP_USERS:
    - PUBLIC_USERS
relatedUsers:
  SHISHUPAL:
    - ADMIN_USER
    - ADMIN_TEXT_DISPLAY_USERS
    - APP_USERS
    - PUBLIC_USERS
